name: subway_simulator_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: 0.4.4
  cloud_firestore: ^0.13.3
  provider: ^4.0.4
  url_launcher: ^5.4.2
  pedantic_mono: ^1.8.0
  transparent_image: ^1.0.0
  flutter_icons: ^1.0.0+1
  animations: ^1.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: any
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/

